### ISSUE TITLE
embeded source error

### ISSUE THREAD

**Issue by daewon** [Raynes/refheap#100]
i'm using refheap's source to my tumblr.
than i account error 

'Uncaught ReferenceError: jQuery is not defined'

because tumblr use jQuery as variable names '$'

i think, fix the source "pastes.js"'s last line

(window, jQuery)  ==> (window, jQuery || $)

**Comment by Raynes** [comment]
This should be fixed now. I added a real embedding mechanism similar to what gist uses. Please use it instead.
