### ISSUE TITLE
Support .cljs as ClojureScript

### ISSUE THREAD

**Issue by mihneadb** [Raynes/refheap#125]
It would be useful to add cljs as well.

Thanks!

**Comment by gf3** [comment]
I don't believe [Pygments](http://pygments.org) supports ClojureScript independent from Clojure. Right now they're [both mapped to Clojure](https://github.com/Raynes/refheap/blob/master/src/refheap/highlight.clj#L9).

**Comment by Raynes** [comment]
I mean, we can certainly add a separate 'ClojureScript' option, but it's going to just be the Clojure lexer.

**Comment by mihneadb** [comment]
Ok, then it must mean I was testing this in a wrong way.

Thanks!

On Thu, Jan 30, 2014 at 10:03 PM, Gianni Chiappetta <
notifications@github.com> wrote:

> I don't believe Pygments http://pygments.org supports ClojureScript
> independent from Clojure. Right now they're both mapped to Clojurehttps://github.com/Raynes/refheap/blob/master/src/refheap/highlight.clj#L9
> .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/Raynes/refheap/issues/125#issuecomment-33727034
> .

## 

Mihnea Dobrescu-Balaur

**Comment by Raynes** [comment]
Oh, what's up? API issues? If so, could you explain what you're trying to do and what isn't working?

Thanks! :dancers:

**Comment by mihneadb** [comment]
IMHO that's the optimal tradeoff.

On Thu, Jan 30, 2014 at 10:05 PM, Anthony Grimes
notifications@github.comwrote:

> I mean, we can certainly add a separate 'ClojureScript' option, but it's
> going to just be the Clojure lexer.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/Raynes/refheap/issues/125#issuecomment-33727324
> .

## 

Mihnea Dobrescu-Balaur

**Comment by mihneadb** [comment]
I'm pretty sure the API is fine and that the problem is on my side.

I made my first LightTable plugin[1], a plugin for posting to Refheap and
it seems like the language part is broken.

[1]
https://github.com/mihneadb/lighttable_refheap/blob/master/src/lt/plugins/refheap.cljs#L38

On Thu, Jan 30, 2014 at 10:12 PM, Anthony Grimes
notifications@github.comwrote:

> Oh, what's up? API issues? If so, could you explain what you're trying to
> do and what isn't working?
> 
> Thanks! [image: :dancers:]
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/Raynes/refheap/issues/125#issuecomment-33727951
> .

## 

Mihnea Dobrescu-Balaur

**Comment by Raynes** [comment]
Ah, I see. Perhaps the extension is missing the dot at the beginning? Refheap uses that dot to decide that the string is an extension rather than a language name.

**Comment by mihneadb** [comment]
Whoops! That was it. Thanks! :)

On Thu, Jan 30, 2014 at 10:19 PM, Anthony Grimes
notifications@github.comwrote:

> Ah, I see. Perhaps the extension is missing the dot at the beginning?
> Refheap uses that dot to decide that the string is an extension rather than
> a language name.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/Raynes/refheap/issues/125#issuecomment-33728727
> .

## 

Mihnea Dobrescu-Balaur

**Comment by Raynes** [comment]
No problem m8. Thanks for writing this plugin! Someone was asking for one very recently. Ping me when you release it and I'll tweet/retweet about it and whatnot!

**Comment by mihneadb** [comment]
It's on the plugin list since yesterday night, I only announced it on
LT-discussion. Feel free to tweet :)

Again, GJ on refheap!

On Thu, Jan 30, 2014 at 10:25 PM, Anthony Grimes
notifications@github.comwrote:

> No problem m8. Thanks for writing this plugin! Someone was asking for one
> very recently. Ping me when you release it and I'll tweet/retweet about it
> and whatnot!
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/Raynes/refheap/issues/125#issuecomment-33729236
> .

## 

Mihnea Dobrescu-Balaur
