### ISSUE TITLE
I'm having trouble using curl to paste a paste to refheap.com.

### ISSUE THREAD

**Issue by trusktr** [Raynes/refheap#126]
I'm trying to do this:

```
curl --request POST 'https://refheap.com/api/paste' --data 'contents=blah blah&username=trusktr&token=55018531-dbe1-41c3-887c-e7ab9e518cc8&private=false&language=text'
```

but the response is this:

```
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/0.7.65</center>
</body>
</html>
```

Am I doing it wrong?

**Comment by Raynes** [comment]
You have to either follow redirects or use the uri: `https://www.refheap.com/api/paste`. Note the `www`. This is the canonical refheap hostname.

**Comment by prepor** [comment]
POST https://refheap.com/api/paste => 404
POST http://www.refheap.com/api/paste => 404
POST https://www.refheap.com/api/paste => yes!

Not very friendly API :)

**Comment by prepor** [comment]
Also, documentation's version is wrong https://github.com/Raynes/refheap/wiki/Documentation:-API

**Comment by Raynes** [comment]
Well, the problem with the first two is that your http client isn't following redirects. I had to change the base URL over time for various reasons. All of those things have redirects.

What do you mean by "documentation's version is wrong"?

**Comment by Raynes** [comment]
Oh, I see. I'll fix that!

**Comment by prepor** [comment]
Oh, i see too :) My client supports redirects and that's the problem. I sent POST https://refheap.com/api/paste and i was redirected to GET https://www.refheap.com/api/paste (because you can't redirect to POST actions).

This is uncommon behaviour and, i think, this is bad practice for API.

**Comment by Raynes** [comment]
Oh, I didn't realize these were POSTs. Apologies.

What exactly do you think is 'bad practice' for the API though? The fact that it is returning a 301 regardless of the fact that you can't actually redirect? What do you propose I do here? You're hitting the wrong URL. I can't really do much besides try to redirect you.

**Comment by causal-agent** [comment]
According to HTTP/1.1, a 307 redirect should make another request with the
same method. See https://tools.ietf.org/html/draft-ietf-httpbis-p2-semantics-21#page-56.

**Comment by Raynes** [comment]
That's not a bad idea.
