### ISSUE TITLE
Social buttons

### ISSUE THREAD

**Issue by Raynes** [Raynes/refheap#13]
Tweet buttons and such on paste pages. What besides a tweet button would be useful here? Facebook? Google+?

**Comment by amcnamara** [comment]
along these lines it would be cool to track the social reach of popular pastes, ie. '9 people have tweeted this paste recently' etc.

**Comment by gf3** [comment]
I think in reality, for the people using this service, these types of buttons and widgets are just noise on the page.

**Comment by Raynes** [comment]
Agreed. Closing.
