### ISSUE TITLE
Problems with login after modifying emails in Persona

### ISSUE THREAD

**Issue by gixxi** [Raynes/refheap#133]
Hi there,

my username for refheap is gixxi. After I removed an email and added a new one (christian.meichsner[at]live.com) i get forwarded to a page which states

"You're almost there! Just enter a username and you'll be on your way."

when I enter "gixxi" then I get forwarded to a page with URL https://www.refheap.com/user/create

that shows the error "Insert fancy 404 image here."

![image](https://cloud.githubusercontent.com/assets/3352923/4418710/8d5c1e1a-4562-11e4-90b0-39c36ec78d09.png)

Kind regards
Christian

**Comment by causal-agent** [comment]
Each user account is associated with one email address that is used to sign in through Persona, and that is the only information we get. I'm not sure how this could be solved other than manually swapping the email address associated with your user account.

**Comment by causal-agent** [comment]
Sorry for the delay by the way!

**Comment by gixxi** [comment]
Hi Curtis,
thanks for getting back on me - It would be so great if you could swap the email accounts
Here is my old data
email christian.meichsner@informatik.tu-chemnitz.de user gixxi
And this is the new account
email christian.meichsner@live.com user gixxi
By the way, I like refheap very much and would like to thank you for your great effort in providing this
Kind regardsChristian

Date: Wed, 15 Oct 2014 21:09:31 -0700

**Comment by causal-agent** [comment]
I updated your email address in the database. You should be able to log in with it now.

**Comment by gixxi** [comment]
Hi Curtis,
appreciate that - thanks
Kind regardsChristian

Date: Sat, 18 Oct 2014 14:23:08 -0700
