### ISSUE TITLE
clarification on wiki?

### ISSUE THREAD

**Issue by jsomedon** [Raynes/refheap#137]
I am trying to understand what it means:

All POSTed parameters are generally expected to be form urlencoded in the body. Refheap will not accept multipart form data.  --- from wiki section Documentation: API

Could some one come up with an example? There is Clojure code in wiki but I don't know how to write it in plain http request message.

**Comment by causal-agent** [comment]
The API accepts POST bodies with `Content-Type: application/x-www-form-urlencoded`, but not `Content-Type: multipart/form-data`. Generally this means you shouldn't be trying to attach a file when you make your request, but should be sending the data as a string value.

**Comment by jsomedon** [comment]
thanks @programble ! So should my post request message headers be private, language, contents, Content-Type?

**Comment by causal-agent** [comment]
You want your HTTP request to look something like this:

```
POST /api/paste HTTP/1.1
Host: refheap.com
Content-Type: application/x-www-form-urlencoded

private=false&language=Clojure&contents=this%20is%20some%20code
```

**Comment by jsomedon** [comment]
Super! Thanks!
