### ISSUE TITLE
Allow users to change usernames

### ISSUE THREAD

**Issue by amcnamara** [Raynes/refheap#16]

**Comment by Raynes** [comment]
Do we really need to do this? It seems to me that it makes things more complicated than necessary. How often would someone need to change their username on a pasting website? I'm not convinced that we need a UI for this, but I'd entertain arguments. My reasoning is that, in the (definitely going to be rare) event that someone needs a username change, we can just do it ourselves. It is a really simple database update.

**Comment by amcnamara** [comment]
I suppose that's true, if we can steer away from an 'account settings' page all the better.  Closing.
