### ISSUE TITLE
Put meaningful data in the right-main content

### ISSUE THREAD

**Issue by amcnamara** [Raynes/refheap#17]
The right content pane on the paste page is prime real-estate; we should put something useful in there.

IDEAS:
- Leave instructions in there until a user signs in
- Put a listing of newest global (or user) pastes
- Put global/user stats for number of pastes, paste average char count, average views, average edits, average forks, etc.
- [edit] See forks of your own pastes.

**Comment by amcnamara** [comment]
this should tie-in with #37

**Comment by gf3** [comment]
Or remove the right-main content area?

**Comment by Raynes** [comment]
@gf3 Bahaha, I was actually coming to say the exact same thing. Yeah, I think that once a user signs in, we should remove that thing completely. Hell, I'm tempted to remove it regardless.

**Comment by gf3** [comment]
@Raynes Indeed!

**Comment by Raynes** [comment]
It is gone. RIP.
