### ISSUE TITLE
Allow for following users

### ISSUE THREAD

**Issue by amcnamara** [Raynes/refheap#18]
By following users their newest pastes could show up in the right-main content pane, this could tie in nicely with issue#17

**Comment by Raynes** [comment]
I'm not really into this. You don't spend a lot of time on a pastebin site. Why would you want to follow people? On something like gist it makes sense because it is just a part of a larger network. I'm not convinced it would work nicely on refheap.

**Comment by amcnamara** [comment]
fair point.
