### ISSUE TITLE
pygments via Jython

### ISSUE THREAD

**Issue by Raynes** [Raynes/refheap#2]
Eventually, it would be quite a bit more optimal to use pygments via Jython rather than shelling out to pygmentize. Low priority.

**Comment by Raynes** [comment]
So it appears that using Jython for this is just insanely slow. It takes around 20 seconds to highlight a 655 line Java file on my machine. I'm not sure there are many ways to speed it up and keep it self contained. Mostly, I think Jython is just slow as hell.

We're probably better off sticking with shelling out to Python.

**Comment by michalmarczyk** [comment]
Whoa, that is bad. I'll let you know if I manage make it faster
somehow, but for now, sure, definitely better to keep shelling out.

On 25 June 2012 00:10, Anthony Grimes
reply@reply.github.com
wrote:
