### ISSUE TITLE
Make custom .syntax highlighting style to match site palette more closely.

### ISSUE THREAD

**Issue by amcnamara** [Raynes/refheap#23]

**Comment by Raynes** [comment]
I [hacked together](https://github.com/Raynes/pygments-tomorrow-night-bright) a tomorrow-night-bright style for Pygments earlier. I really like it. I think we should also do a tomorrow-night-light color theme as per #38. The great thing about tomorrow-night is that the colors are defined for all of the themes. We could implement the whole set and make them switchable if we wanted. Furthermore, they are fairly popular themes. It is hard to find people who don't like any one of them, much less all of them.

If you agree, I think we can close this issue. The new color theme is in production, so check it out.

**Comment by amcnamara** [comment]
I'm going to close this since our theme seems pretty locked down, will get #38 done using what we've got.
