### ISSUE TITLE
Zoomed text + line numbers is wonky on Chrome on certain platforms

### ISSUE THREAD

**Issue by Raynes** [Raynes/refheap#30]
@amalloy notes that line numbers don't line up with code properly in Chrome on his Ubuntu box with zoomed in text.

**Comment by Raynes** [comment]
This is low priority because it is actually a Chrome bug. We might not be able to fix it at all. The site renders just fine regardless of zoom in Firefox and I expect IE as well.

**Comment by amcnamara** [comment]
This should be fixed with the new css patch.
