### ISSUE TITLE
An editor for the pastebox

### ISSUE THREAD

**Issue by Raynes** [Raynes/refheap#34]
@programble mentioned that having an actual editor for the pastebox might be useful. We should look into what Github uses for editing files via the web UI. I'm pretty sure its open source. @cmeier has done some work with this sort of thing on 4Clojure and might be able to help us out.

**Comment by causal-agent** [comment]
[This](http://ace.ajax.org/), if their site would actually work...

**Comment by amcnamara** [comment]
Yeah, ACE is what github and 4clj use.  It can be a bit of a pain wrt styling iirc.  I'd also consider a code formatter on the server side if such a library exists.

**Comment by Raynes** [comment]
I think we're definitely going to do this. Just not priority. Marking it as low priority.

**Comment by Raynes** [comment]
http://codemirror.net/

I'm going to work on this soon.

**Comment by Raynes** [comment]
Done.
