### ISSUE TITLE
multi-file paste

### ISSUE THREAD

**Issue by Raynes** [Raynes/refheap#35]
Someone mentioned that this would be useful. I'm not convinced. It seems to me that it complicates things unnecessarily.  For example, the API would be complicated by it. Not just for us, but for users as well. Is it really useful enough to warrant the complexity?

**Comment by Raynes** [comment]
Yeah, I'm not in to this. @amcnamara what do you think? I've thought about it for a couple of days and it still seems like the complexity it adds blows away any possible benefits.

**Comment by amcnamara** [comment]
Not really, with the api users have the option to script this behaviour themselves; but it's not worth complicating the UX.  Also, pastebins aren't really ideal for tracking granular files.  Closing.
