### ISSUE TITLE
Allow for Github as an alternative login

### ISSUE THREAD

**Issue by Raynes** [Raynes/refheap#39]
I'm not sure about this one. BrowserID, though not very adopted yet, is so easy to set up the first time that I'm not sure anyone can really complain about it. That said, there is some coolness factor to being able to login to sites with Github. Perhaps we should add it as an alternative to browserID. It'd take some slight UI reworking.

If we do, definitely low priority.

**Comment by amcnamara** [comment]
Github login sounds out of place, since they also have a paste service of their own.

**Comment by Raynes** [comment]
Using the internet as a medium for refheap feels out of place because (don't look now, but) there are other pastebins on the internet as well! We need to implement a new internet protocol! Quick, before they get us!

EDIT: Damned "Close & Comment" button.

**Comment by Raynes** [comment]
This is a bad idea. It'll complicate things more than it'll improve them. BrowserID is easy enough. Closing.
