### ISSUE TITLE
Organize language dropdown to put more important languages first

### ISSUE THREAD

**Issue by Raynes** [Raynes/refheap#40]
Clojure, Haskell, HTML, CSS, JS, C, C++, C#, Ruby, Python, Perl, Sheme, XML,  Scala, Erlang, IRC Logs. Not necessarily in that order. I'd put the markup languages and IRC logs towards the bottom, Clojure at the very top followed by the other languages. This list is not absolute, adjustments can be made.

**Comment by amcnamara** [comment]
I'm against screwing with alphabetical order... it's bad voodoo.

**Comment by Raynes** [comment]
I think at least two people have complained about it so far. I absolutely agree and would rather leave it the way it is, but if people keep being bothered by it, we'll probably have to do it. I'll tag this with maybe for now.

**Comment by amcnamara** [comment]
If they're so concerned about speed tell them to click on the box and start typing, that's how the cool kids do it.

**Comment by Raynes** [comment]
![cool kid](http://profile.ak.fbcdn.net/hprofile-ak-snc4/50313_174571009223900_7495065_n.jpg)

**Comment by Raynes** [comment]
Since I added the chosen dropdown thingy, I don't think this matters anymore. I know of only one person who furiously disagrees, so I think we're good. Closing.
