### ISSUE TITLE
Easier edit workflow

### ISSUE THREAD

**Issue by amcnamara** [Raynes/refheap#41]
- Double clicking on paste content should bring you to the edit page
- Bonus points: position the cursor/caret wherever was clicked in the syntax box... getting a proper raw position out of pygments might be ridiculously hard though

**Comment by Raynes** [comment]
@apgwoz mentioned that he might have code somewhere for your second bullet point.

**Comment by apg** [comment]
I never did find that. I've got one more place to look though.

**Comment by Raynes** [comment]
#46 replaces this issue, I think. Keyboard shortcuts seem like the easier and more streamlined way to approach this unless we do figure out how to edit only a single pygments line.
