### ISSUE TITLE
Resizing on large screens

### ISSUE THREAD

**Issue by Raynes** [Raynes/refheap#45]
I was talking to a guy in #clojure about how he likes refheap. His only concern is how the site looks on large screens. @amcnamara we have a maximum size, don't we? Why is that again? Looking at the site on my TV (bigger than my laptop), it does kind of look like ass. Can't we just resize? I know that the paste box would be humongous, but I'm okay with that.

I'd appreciate if you could play around with that.

@jeremyheiler would be the nice fellow who pointed this out. He might have more comments. Jeremy, think you could screenshot the site for us?

**Comment by jeremyheiler** [comment]
Sure. The window is full-screen: http://i.imgur.com/nO2HL.png

I care more about the height (as I don't always have my browser windows that wide) but it would be nice to have the paste area fill whatever empty space is available. I can see msyelf using refheap as more than just a pastebin, but as a place to compose notes and example code directly in-browser. So, more space is a big plus!

Edit: My resolution is 1920x1080.

**Comment by amcnamara** [comment]
Yeah, that does look wonky.  I'll get on this tomorrow night.

**Comment by Raynes** [comment]
Awesome. :)

**Comment by Raynes** [comment]
@amcnamara When do you think you'll have a chance to look at this? This is the longest tomorrow night I've ever been through. Like groundhog day or some shit. :P

**Comment by amcnamara** [comment]
Actually, I said I'd do it right after I had a shower... 2 weeks ago.  If anything, it's the world's longest shower.

See commit 11bc, let me know if you get any rendering issues (I tested on the biggest screen I've got, but that's only 1050px high).

**Comment by Raynes** [comment]
@amcnamara I investigated that commit a bit. The reason the scrollbar appears is because you've set `overflow: auto` on the site container. When I resize my browser window vertically, I end up with a bunch of space at the bottom of the site.

I think we need keep the min-height the same as the max height we currently have. It looks like shit any smaller. Thoughts? (Whenever, I know you're busy until this weekend)

**Comment by gf3** [comment]
I'm not sure how it looks on a screen that large, but I used a few simple media queries to deal with different screen sizes, feel free to borrow.

**Comment by gf3** [comment]
Er, I should mention, that I used them on [cljbin](http://cljbin.com/).

**Comment by ghost** [comment]
https://github.com/Raynes/refheap/pull/77

**Comment by jeremyheiler** [comment]
I "applied" the patch directly in Chrome on refheap.com, and I most definitely approve of this.

**Comment by Raynes** [comment]
@jeremyheiler @autodidakto I think you'll both be exceedingly pleased with what I've done. Let me know what you think.

**Comment by ghost** [comment]
Ahh, good solution. Kudos.

**Comment by jeremyheiler** [comment]
I think autodidakto's solution is more elegant, but I like how Raynes made it full screen. Either way, its an improvement!

**Comment by Raynes** [comment]
@jeremyheiler His solution opened up other problems though. If you paste long code, you end up getting thrown to the bottom of the page. Furthermore, it feels weird to have the whole thing expand to the size of code instead of the size of the screen.

**Comment by jeremyheiler** [comment]
Fair enough.
