### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by Raynes** [Raynes/refheap#46]
We should have keyboard shortcuts for as many functions as we possible can. Especially copying.

**Comment by ghost** [comment]
I'm going to take this issue on.  Based on an IRC conversation, the following shortcuts have been requested:
- ! Regular copy and paste already work
- Navigate from owned-paste page to edit page of that paste
- Copy raw contents of paste to clipboard
- Toggle private
- POST the paste
- Take logged in user to homepage
- go-to-line

**Comment by ghost** [comment]
See https://github.com/Raynes/refheap/pull/82

**Comment by Raynes** [comment]
@wkmanire @michaelklishin reports that pressing 'cmd' on his OS X box using any browser results in the goto-line prompt opening. Any idea what could be causing this? I haven't seen this behavior, and I've not heard any other reports of it. I seem to recall someone mentioning pressing 'alt' would cause something similar to happen though.

**Comment by Raynes** [comment]
@michaelklishin Can you pull develop and see if switching to Mousetrap fixed things?

(SHA bf0379fe859bcb052f21e6a6ada6d312d6938a74)

Also, does this happen on the production site or just with your local copy? What keyboard layout, page, etc.
