### ISSUE TITLE
Pastes made in an anon session should be assigned to user on login.

### ISSUE THREAD

**Issue by amcnamara** [Raynes/refheap#5]
If a user makes a paste before logging in, and then subsequently logs in, that paste should be assigned to that user.

NOTE: Might be a good idea to make this optional, and/or give the option to make them immediately private or something.  This should be thought out deliberately.

**Comment by Raynes** [comment]
I think just giving users ownership should be okay. We've added the ability to make anonymous private pastes, so if they fail to make it private, they've already screwed up.
