### ISSUE TITLE
Set default language per-user

### ISSUE THREAD

**Issue by Raynes** [Raynes/refheap#50]
We should add the default language as a setting for users.

@amcnamara Might want to start thinking about where we'd put a setting like this.

**Comment by amcnamara** [comment]
This would be best stored in a cookie, presumably.   I don't see any good reason to store this server-side, other than continuity across browsers (not a huge deal).

**Comment by Raynes** [comment]
Sounds good to me. If we store it in a cookie, we don't necessarily have to have a setting. Would it be fair to just keep track of the language the user last selected? Or perhaps the language the user has used most? Either of these would be easy to implement. If it seems reasonable (and I think it is, given that we have the lang parameter), I'd like to avoid having a setting.

**Comment by amcnamara** [comment]
I'd go with last used, it's the most straightforward.
