### ISSUE TITLE
Staying logged in

### ISSUE THREAD

**Issue by Raynes** [Raynes/refheap#51]
We're using a session to store logged in info, so it gets wiped when the browser is closed. Is this bad? Should we use a cookie that sticks around forever/a long time?

@amalloy What do you do in 4Clojure?

**Comment by amalloy** [comment]
We use session cookies too, but only because we don't know how to set permanent cookies.

**Comment by Raynes** [comment]
@amalloy I'll learn how and get back to you.

**Comment by amcnamara** [comment]
update?

**Comment by Raynes** [comment]
I forgot I was supposed to do something about this. Feel free to do it if you want. I'll get to it eventually if you don't.

**Comment by amcnamara** [comment]
remind me on saturday, I've got a few things I want to tackle this weekend and I'll add this to the list.

**Comment by Raynes** [comment]
@amcnamara Remind'd

Don't feel obligated to get it done if you're too busy though. Shit happens.

**Comment by amcnamara** [comment]
This won't get done for a while.

**Comment by Raynes** [comment]
Meh. #5 is a better solution to this problem. The only reason you'd want to be logged in would be to take ownership of a paste.
