### ISSUE TITLE
Editing pastes changes language and privacy

### ISSUE THREAD

**Issue by netherokk** [Raynes/refheap#60]
When editing a paste, the Language and Privacy fields always default to Clojure and false instead of what are stored for the paste. It would be nice to have these fields updated to the paste settings to avoid accidentally saving with the wrong language.

**Comment by Raynes** [comment]
Yeah, they are supposed to be. I noticed this bug a few days ago after I moved to Mustache for templating, but I forgot about it. Thanks for reminding me, I'll get on this ASAP.
