### ISSUE TITLE
Build-in URL Shortener

### ISSUE THREAD

**Issue by kremers** [Raynes/refheap#69]
A shortened URL ready to copy and paste with a shortcut is nice after a snippet is posted.
Maybe goo.gl supports that via api?

http://goo.gl/

**Comment by Raynes** [comment]
I've actually been considering writing a simple little URL shortener myself for a couple of unrelated reasons. Perhaps those could be integrated. This would be simple in any case with generally any URL shortener.

**Comment by kremers** [comment]
Maybe just embedding goo.gl API is a quick win

http://code.google.com/intl/de-DE/apis/urlshortener/v1/getting_started.html#shorten

**Comment by Raynes** [comment]
I've thought about this a bit and here are my current thoughts:

This is dead easy to implement. Any URL shortener would do. That isn't an issue. I'm just curious as to whether or not this is a useful feature for RefHeap itself to have. My rationale is that there is a browser plugin for any given x url shortener on any given y browser. For example, I have a bitly chrome extension installed and all I have to do is click the icon in the upper right corner and I have a shortened link to my paste. This solves the problem entirely for me.

I don't think it's worth clogging up the UI with more buttons/links/etc.
