### ISSUE TITLE
Middle-click to paste on Linux

### ISSUE THREAD

**Issue by relrod** [Raynes/refheap#76]
This is one of those things where to anyone who doesn't use it every day it seems like a really silly request, but if you use it all the time, it's really frustrating to work around.

Using the JS editor, I cannot middle-click text that is stored in the Xorg clipboard into Refheap. Because it's become habit, for quick copypastes, it's annoying to have to go back and copy it to the gnome clipboard (ctrl-shift-c from the terminal) and I end up just pasting the code somewhere else because it's quicker a lot of times.

So my request, on behalf of middle-click-using Linux users everwhere, is either: Figure out how to make the JS input support middle click paste, or allow logged in users to opt out of the JS input.

**Comment by Raynes** [comment]
An update to codemirror was supposed to fix this. At least in Chrome, anyways. I've deployed it to production but it isn't looking good. @CodeBlock Can you please try middle click paste on the prod site and see if it is working now?

**Comment by relrod** [comment]
Confirming that it's fixed in Chrome, still broken in Firefox :(

**Comment by Raynes** [comment]
@CodeBlock I'm going to go ahead and close it anyways. Not really anything I can do about it until ffx and codemirror work their issues out.

Thanks for checking!
