### ISSUE TITLE
printing

### ISSUE THREAD

**Issue by aaelony** [Raynes/refheap#78]
Sometimes it's nice to be able to print syntax highlighted code on refheap (which is awesome) to paper.  Currently, if code lines are longer than the bounding scroll box then printing leads to incomplete lines making the printout an unusable guessing game.

Would love to see a print button that maintains the syntax highlighting for all the code, or perhaps even a set of clj code on github.  There's nothing like paper in hand to understand complex things, no?

-A

**Comment by Raynes** [comment]
Does this also happen in the 'maximize' view?

**Comment by Raynes** [comment]
Yeah, it happens there too. I'll see what I can do.

**Comment by aaelony** [comment]
You know what, maximize view is pretty cool.  My mistake was that I
wasn't always using the "paste" button.  I'd paste it in and want to
print directly, without storing it. But... once I click the "paste"
button, I can take advantage of maximize view :)

On 4/30/12, Anthony Grimes
reply@reply.github.com
wrote:

**Comment by Raynes** [comment]
It still seems to cut off in the maximize view though, which makes sense because the length of a page is the length of a page.

**Comment by aaelony** [comment]
Yeah, maybe a wrap is possible at the end of page?

On 4/30/12, Anthony Grimes
reply@reply.github.com
wrote:

**Comment by Raynes** [comment]
I'm going to go ahead and close this. I'm not sure what I can do about it. I mean, we _could_ wrap, but it'd be hideous. My reasoning at this point is: if you're going to print your code out, you should make sure it fits on a page. That's a generally accepted convention.

**Comment by aaelony** [comment]
yeah, I'm ok with that. Not optimal but it's a widespread problem.

rant: half the time blogs with those silly embedded github boxes of
code with syntax highlighting don't print properly either - if you try
you get the first 2-3 inches of the left side of the code instead of
coherent sentences.

all in all, there are bigger problems to solve ;)))

On 5/6/12, Anthony Grimes
reply@reply.github.com
wrote:
