### ISSUE TITLE
Hostname lookup uses environment variable instead of config value

### ISSUE THREAD

**Issue by bhiles** [Raynes/refheap#80]
I was getting exceptions when trying to login when I was running refheap locally and using the hostname 127.0.0.1 in my browser.  

The hostname used in the browserID verification is pulled from the environment variables which I never set, so it was defaulting to _localhost_ which isn't the value I wanted to use.

This hostname value should probably be pulled from the configuration file that way you don't need to configure it in multiple places.

**Comment by bhiles** [comment]
I created a pull request, https://github.com/Raynes/refheap/pull/81, to address this issue.

**Comment by Raynes** [comment]
Closing this because your pull request was merged.
