### ISSUE TITLE
Make what the line count is clearer

### ISSUE THREAD

**Issue by roryokane** [Raynes/refheap#84]
I’m talking about the lone number in the top-left, between the language name and the paster name. [Example paste with a line count](https://www.refheap.com/paste/3141). When I first visited the site, I was briefly confused what that number was. I would have been confused even longer if the first paste I saw had been a long paste where I couldn’t see the line number of the final line.

[Here](https://github.com/Raynes/refheap/blob/develop/src/refheap/views/templates/pasted.mustache#L5) is the line in the template that writes that part. Possible different versions:

``` html
<li>{{lines}} lines</li>
```

``` html
<li><span title="{{lines}} lines">{{lines}}</span></li>
```

``` html
<li><span title="{{lines}} lines in this paste">{{lines}}</span></li>
```

``` html
<li><span title="{{lines}} lines in this paste">{{lines}} lines</span></li>
```

**Comment by Raynes** [comment]
Agreed. It did at some point say "Lines: n" but someone changed it.

I wonder if just `57L` would have been clearer. Thoughts?

**Comment by roryokane** [comment]
I considered and rejected `57l` but forgot to consider `57L`. I think `57 L` looks best. I also think the line count should have a `title` to explain what “L” is. And since “L” is an abbreviation, we should use the `<abbr>` tag. So overall, it would be

``` html
<li><abbr title="{{lines}} lines in this paste">{{lines}} L</abbr></li>
```

`<abbr>` also gets a dotted bottom border (looks like an underline) by default, which doesn’t look good here, so we would need this new CSS:

``` css
#infolist abbr {
  border-bottom-style: none;
}
```

**Comment by Raynes** [comment]
Excellent. Sounds perfect.
