### ISSUE TITLE
Make it clearer that “Latest” is latest pastes

### ISSUE THREAD

**Issue by roryokane** [Raynes/refheap#85]
When I first visited the site, I wanted to see an example paste, to see what styling and features the site offered for existing pastes. I looked for a link that would let me see an example paste, but none of the header options “Latest”, “API”, or “About” seemed right. I thought “Latest” would be a blog of the latest changes to the site or something, so I looked in “About”. Only when I saw that that didn’t have any code did I try “Latest”.

I think a better name for that link would help. [Here](https://github.com/Raynes/refheap/blob/develop/src/refheap/views/templates/common.mustache#L14) is the code for the link in the header. Possible alternatives to “Latest”:
- Pastes
- Public Pastes
- Latest Pastes

I’m not sure if the site offers a page to see all of _your_ pastes when you have signed in. if it does, that would affect what name is appropriate, depending on whether the “your pastes” page takes over the `/pastes` page or is on another page. (If it exists and is in another page, I’m surprised it doesn’t have a link in the header.)

There is the danger that if the header doesn’t include “Latest”, people won’t know that these are the _latest_ pastes they are seeing (as opposed to a random selection or a curated list of best examples). To fix that, that page should have a header of its own. Here is an example with a changed header link and an added page title:

![proposed header of Latest Pastes](http://i.imgur.com/mFYmy.png)

The page title “Latest Pastes” in the picture uses the default style for an `<h1>`. I think it would need some restyling before use – at least, removal of some whitespace above it.

**Comment by Raynes** [comment]
I agree that 'Pastes' is a much better word to use there. After you sign in, the sign in button disappears and is replaced with a link to the user paste page and a logout link.
