### ISSUE TITLE
move refheap.middleware to noir?

### ISSUE THREAD

**Issue by davesann** [Raynes/refheap#87]
Just a thought

(particularly force-ssl)

D

**Comment by Raynes** [comment]
@ibdknox Anything in refheap.middleware you'd like to see in noir?

**Comment by Raynes** [comment]
I think it's all generally useful and would be happy to put it all in noir. The only thing I see that would need to change would be to remove the code that checks for the `CANONICAL_HOST` env var in `wrap-canonical-host`, instead making it an argument.

**Comment by Raynes** [comment]
Done in lib-noir 0.2.0-alpha1.
