### ISSUE TITLE
Idea: Word wrap

### ISSUE THREAD

**Issue by zokipirlo** [Raynes/refheap#97]
I think it would be helpful to have a option for word wrapping. I hate long horizontal scrollers.

**Comment by Raynes** [comment]
Done. I implemented this as a keyboard shortcut because I don't see a good place to add it to the UI. I don't think we need a UI addition because I doubt this will be used a whole lot. Right now it is triggered with `alt+w`, but I could also add a query parameter that triggers it per request.

**Comment by zokipirlo** [comment]
Great, tnx.

**Comment by Raynes** [comment]
I will also eventually be adding a place to set options like this and default language in the user page.

**Comment by Raynes** [comment]
Gonna reopen this because I should add word wrapping to the pasted code too. What I did only works for the code box at the moment.

**Comment by Raynes** [comment]
Pygments makes word wrapping pastes with line numbers pretty impractical (nearly impossible). The actual text can be word-wrapped easily, but the line numbers can't be aligned with the text properly. I'm not going to bother.
