### ISSUE TITLE
Normalize.css

### ISSUE THREAD

**Issue by Raynes** [Raynes/refheap#98]
The css for the site would probably be easier to write/maintain if it were rewritten in the context of normalize.css. Someone familiar with it will have to take up this issue.

**Comment by sergiotapia** [comment]
You just need to reference the file and then in your actual CSS customize whatever you need.
1. Reference this: https://raw.github.com/necolas/normalize.css/master/normalize.css
2. Create a style.css for your actual styles.

**Comment by Raynes** [comment]
Well, yeah. The biggest issue is the amount of css we might have already written that is unnecessary with normalize.css (we've never used a reset or anything). I'm not familiar with normalize, so it'd take me quite a while to clean the css up and that's why I figured I'd toss it out for someone with more experience with it to take up.
