### ISSUE TITLE
Use my browser's default monospace font

### ISSUE THREAD

**Issue by uvtc** [Raynes/refheap#99]
I've already carefully chosen my browser's default monospace font, and it would be nice if refheap just let me have my way on this matter. :)

**Comment by Raynes** [comment]
I purposely avoided using the browser's default font because some of the fonts people let their browsers use are pretty terrible.

That said, I'm sure there is something we can do. Maybe a way to toggle it to use your default font.

**Comment by uvtc** [comment]
Considering that it's a site for programmers, my guess is that your average refheap user has probably already customized their browser's default monospace font.

However, here's an alternative: I see in that in the top right of every paste there are some links ("embed", "raw", "maximize"). How about if the maximize link used the browser's default monospace font?

**Comment by Raynes** [comment]
I don't think that is a fair assumption. I don't know a lot of programmers who have set their browser's monospace font. I certainly haven't.

I think that whatever we do should be consistent.

**Comment by uvtc** [comment]
Wait a sec. This is odd...

I've always wondered why the font appeared somewhat aliased.

If I zoom the page a bit, the font now looks normal, antialiased, and fine.

**Comment by uvtc** [comment]
Ok, if I zoom a little it's alright.

Would still be nice to have a combo box (in that row of embed/raw/maximize links) to let the user choose a monospace font. Two nice alternative fonts are Inconsolata and Ubuntu Mono (incidentally, I see that both are available via google webfonts).
